### ISSUE TITLE
How to build & test this approach in local environment?

### ISSUE THREAD

**Issue by duongvu89** [awslabs/ecs-refarch-service-discovery#14]
This is a question. Thanks.

**Comment by schmutze** [comment]
Hi,

The [README.md](https://github.com/awslabs/ecs-refarch-service-discovery/blob/master/README.md) and corresponding [blog post](https://aws.amazon.com/blogs/compute/service-discovery-an-amazon-ecs-reference-architecture/) should have all you need to launch this reference architecture in your own AWS environment.

thanks,
chad
