### ISSUE TITLE
No CNAME

### ISSUE THREAD

**Issue by lucacome** [awslabs/ecs-refarch-service-discovery#2]
I followed every step, but at the end there are no CNAME in Route53, so it's not working. After adding the CNAMEs manually everything works fine.

I've never used Lambda and CloudWatch before and I couldn't find a way to debug them, so I don't know where is the problem.

**Comment by zoellner** [comment]
@lucacome you can look at the log output of the lambda function. It is available in CloudWatch logs.
Assuming you have launched in us-east-1 and used the proposed name for the lambda function "registerEcsServiceDns" the logs should be available at: 
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logStream:group=%252Faws%252Flambda%252FregisterEcsServiceDns

**Comment by lucacome** [comment]
@zoellner unfortunately there's nothing there, that's why I was asking how to debug.

**Comment by clubdesign** [comment]
Can confirm that problem. Everything worked out fine, but i don`t see Any Events in the Lambda Logs.
The Portal is loading fine, but not the Microservices. If i open the Cloudwatch Event and look into the Rule created for the Lambda and click "Show metrics of rules" there is nothing in there.

Can anybody clear things up?

**Comment by lucacome** [comment]
Seems to be working for me now, after enabling CloudTrail.

**Comment by clubdesign** [comment]
How did you enable Cloudtrail?

**Comment by clubdesign** [comment]
This solved the issue for me too. Grmbl. (Banging head to the wall)

**Comment by schmutze** [comment]
Thank you everyone. 

I've added enabling AWS CloudTrail as a prerequisite in the README here:
https://github.com/awslabs/ecs-refarch-service-discovery/commit/069bc77d9f24c9d8766ee1f070eab82eac8ec478
