### ISSUE TITLE
Get rid of ELB

### ISSUE THREAD

**Issue by vankhoa011** [awslabs/ecs-refarch-service-discovery#4]
I want to use Route 53 for load balancing. And I don't need use ELB for load balancing.  Is it possible ?

**Comment by schmutze** [comment]
Hi @vankhoa011,

What you've described is possible, but slightly out of scope for this particular reference architecture as the goal was to highlight integration between ECS and ELB.

Let me give this some thought and perhaps we can produce a future reference architecture that implements the design you've described.

thanks,
chad
