### ISSUE TITLE
Question the capability for production system

### ISSUE THREAD

**Issue by allinwonder** [awslabs/ecs-refarch-service-discovery#7]
To be honest, I am not comfortable to use this solution in my environment.for the following reasons
- The complexity of this architecture requires extensive knowledge of AWS services, Lambda, CloudWatch Event, CloudTrail, ECS, Route53 + Private Hosted Zone. For a dynamic team environment, this requires non-trivial effort for the engineers to pick up and maintain.
- The visibility of the operation and automation is very poor. There are quite a lot of places can go wrong in the picture, but the monitoring is the biggest part missing from this project. For example, Lambda function failure, Lambda invocation throttle, Route53 rate limit, CloudTrail delivery failure, CloudWatch Event invocation failure. I don't think this is fun for our engineer to diagnostic failures in the production at 2 AM and go through all these component to find out what goes wrong.  

All in all, I would prefer a more mature solution for service discovery provided as a service from AWS rather than this project.

**Comment by Foolre** [comment]
I wonder if Amazons ALB announced in August 2016 makes this architecture still relevant for HTTP/HTTPS services. Does someone has any answers?

**Comment by schmutze** [comment]
@allinwonder Thank you for your feedback. This is meant to be used as an example architecture, and we'd certainly encourage you to extend as appropriate for your requirements and environment.

@Foolre This architecture can certainly be consolidated with the use of an ALB in place of the ELBs.
